---
# Begin configuration 3tier.
# Must pass GUID from enviroment variable.
#
- name: Configuration.
  hosts: internal
  gather_facts: false
  become: true

  roles: 
  - configuration

- name: Deploy haproxy.
  hosts: frontends
  gather_facts: false
  become: true

  roles:
  - deploy-haproxy

- name: Deploy tomcat.
  hosts: apps
  gather_facts: false
  become: true

  roles:
  - deploy-tomcat

- name: index.html on app 1
  hosts: app1
  gather_facts: false
  become: true

  roles:
  - index-app1

- name: index.html on app 2
  hosts: app2
  gather_facts: false
  become: true

  roles:
  - index-app2

- name: deploy postgres
  hosts: appdbs
  gather_facts: false
  become: true
  
  roles:
  - deploy-postgres


- name: deploy apache
  hosts: apps
  gather_facts: false
  become: true

  roles:
  - deploy-apache
